# Generated by Django 5.0.7 on 2026-01-29 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historico', '0001_initial'),
        ('operativos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participacion',
            name='operativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='operativos.libro'),
        ),
    ]
