# Generated by Django 5.0.7 on 2026-01-31 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0003_historicalparticipacion'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historicalparticipacion',
            table='participacion_historicos',
        ),
    ]
