# Generated by Django 5.0.7 on 2026-01-31 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0004_alter_historicalparticipacion_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparticipacion',
            name='origen',
            field=models.CharField(choices=[('V', 'Venezolano'), ('E', 'Extranjero')], default='V', max_length=1),
        ),
        migrations.AddField(
            model_name='participacion',
            name='origen',
            field=models.CharField(choices=[('V', 'Venezolano'), ('E', 'Extranjero')], default='V', max_length=1),
        ),
    ]
