# Generated by Django 5.0.7 on 2026-01-31 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0005_historicalparticipacion_origen_participacion_origen'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historicalparticipacion',
            table='participaciones_historico',
        ),
    ]
