# Generated by Django 5.0.7 on 2026-01-31 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0006_alter_historicalparticipacion_table'),
    ]

    operations = [
        # The table was moved manually to the `historico` schema already.
        # Run a harmless SQL to mark this migration as applied without
        # attempting to execute the invalid ALTER TABLE generated by Django
        migrations.RunSQL(
            sql="SELECT 1;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
