# Generated by Django 5.0.7 on 2026-01-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Descripción')),
                ('estatus', models.BooleanField(default=True, verbose_name='Estatus')),
                ('motivo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo')),
            ],
            options={
                'verbose_name': 'Ente',
                'verbose_name_plural': 'Entes',
                'db_table': 'auxiliares"."ente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstatusOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Descripción')),
                ('estatus', models.BooleanField(default=True, verbose_name='Estatus')),
                ('motivo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo')),
            ],
            options={
                'verbose_name': 'Estatus Operativo',
                'verbose_name_plural': 'Estatus Operativos',
                'db_table': 'auxiliares"."estatusoperativo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Descripción')),
                ('estatus', models.BooleanField(default=True, verbose_name='Estatus')),
                ('motivo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo')),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
                'db_table': 'auxiliares"."lugar',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Descripción')),
                ('estatus', models.BooleanField(default=True, verbose_name='Estatus')),
                ('motivo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo')),
            ],
            options={
                'verbose_name': 'Parentesco',
                'verbose_name_plural': 'Parentescos',
                'db_table': 'auxiliares"."parentesco',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Descripción')),
                ('estatus', models.BooleanField(default=True, verbose_name='Estatus')),
                ('motivo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo')),
            ],
            options={
                'verbose_name': 'Tipo de operativo',
                'verbose_name_plural': 'Tipos de operativos',
                'db_table': 'auxiliares"."tipo_operativo',
                'managed': True,
            },
        ),
    ]
