# Generated by Django 5.0.7 on 2026-01-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Descripción')),
                ('estatus', models.BooleanField(default=True, verbose_name='Estatus')),
                ('motivo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo')),
            ],
            options={
                'verbose_name': 'excepcion',
                'verbose_name_plural': 'excepciones',
                'db_table': 'auxiliares"."excepcion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lista_Negra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Descripción')),
                ('estatus', models.BooleanField(default=True, verbose_name='Estatus')),
                ('motivo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo')),
            ],
            options={
                'verbose_name': 'Lista_Negra',
                'verbose_name_plural': 'Lista_Negra',
                'db_table': 'auxiliares"."lista_negra',
                'managed': True,
            },
        ),
    ]
