# Generated by Django 5.0.7 on 2026-01-29 19:14

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auxiliares', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NominaEntes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(blank=True, choices=[('V', 'Venezolano'), ('E', 'Extranjero')], default='V', max_length=1, null=True, verbose_name='Origen')),
                ('cedula', models.IntegerField()),
                ('nombre_apellido', models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre_apellido')),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(blank=True, max_length=1, null=True, verbose_name='sexo')),
                ('ente', models.CharField(blank=True, max_length=100, null=True, verbose_name='ente')),
                ('clasificacion', models.CharField(blank=True, max_length=1, null=True, verbose_name='clasificacion')),
                ('condicion', models.CharField(blank=True, max_length=1, null=True, verbose_name='condicion')),
                ('entidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='entidad')),
                ('ente_nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='ente_nombre')),
            ],
            options={
                'verbose_name': 'Nomina Ente',
                'verbose_name_plural': 'Nominas Entes',
                'db_table': 'operativos"."nominaentes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VmNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(blank=True, choices=[('V', 'Venezolano'), ('E', 'Extranjero')], default='V', max_length=1, null=True, verbose_name='Origen')),
                ('cedula', models.IntegerField(blank=True, null=True, verbose_name='cedula')),
                ('nombre_apellido', models.TextField(blank=True, null=True, verbose_name='nombre_apellido')),
                ('estado_civil', models.CharField(blank=True, null=True, verbose_name='estado_civil')),
                ('sexo', models.CharField(blank=True, null=True, verbose_name='sexo')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='fecha_nacimiento')),
                ('codigo_estatus', models.CharField(blank=True, null=True, verbose_name='codigo_estatus')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='fecha_ingreso')),
                ('clasificacion', models.CharField(blank=True, null=True, verbose_name='clasificacion')),
                ('codigo_banco', models.CharField(blank=True, null=True, verbose_name='codigo_banco')),
                ('cuenta_banco', models.CharField(blank=True, null=True, verbose_name='cuenta_banco')),
                ('codigo_cargo', models.CharField(blank=True, null=True, verbose_name='codigo_cargo')),
                ('cargo', models.CharField(blank=True, null=True, verbose_name='cargo')),
                ('codigo_dependencia', models.CharField(blank=True, null=True, verbose_name='codigo_dependencia')),
                ('dependencia', models.CharField(blank=True, null=True, verbose_name='dependencia')),
                ('codigo_entidad', models.CharField(blank=True, null=True, verbose_name='codigo_entidad')),
                ('entidad', models.CharField(blank=True, null=True, verbose_name='entidad')),
                ('condicion', models.TextField(blank=True, null=True, verbose_name='condicion')),
            ],
            options={
                'verbose_name': 'Vm Nonina',
                'verbose_name_plural': 'Vm Nominas',
                'db_table': 'operativos"."vm_nomina',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistoricalLibro',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='titulo')),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('motivo', models.CharField(blank=True, max_length=100, null=True, verbose_name='motivo')),
                ('publicado', models.BooleanField()),
                ('ilustracion', models.CharField(blank=True, max_length=100, null=True, verbose_name='ilustracion')),
                ('ilustracion_b64', models.TextField(blank=True, null=True, verbose_name='ilustracion_b64')),
                ('usar_telegram', models.BooleanField(blank=True, null=True, verbose_name='usar_telegram')),
                ('verificado', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('estatus', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auxiliares.estatusoperativo', to_field='descripcion')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lugar', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auxiliares.lugar', to_field='descripcion')),
                ('tipo_operativo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auxiliares.tipooperativo', to_field='descripcion')),
            ],
            options={
                'verbose_name': 'historical Libro',
                'verbose_name_plural': 'historical Libros',
                'db_table': 'libro_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='titulo')),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('motivo', models.CharField(blank=True, max_length=100, null=True, verbose_name='motivo')),
                ('publicado', models.BooleanField()),
                ('ilustracion', models.CharField(blank=True, max_length=100, null=True, verbose_name='ilustracion')),
                ('ilustracion_b64', models.TextField(blank=True, null=True, verbose_name='ilustracion_b64')),
                ('usar_telegram', models.BooleanField(blank=True, null=True, verbose_name='usar_telegram')),
                ('verificado', models.BooleanField(default=False)),
                ('estatus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estatus_opeerativo', to='auxiliares.estatusoperativo', to_field='descripcion')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lugar', to='auxiliares.lugar', to_field='descripcion')),
                ('tipo_operativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipo_operativo', to='auxiliares.tipooperativo', to_field='descripcion')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'managed': True,
            },
        ),
    ]
