# Generated by Django 5.0.7 on 2026-01-25 01:00

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0002_excepcion_lista_negra'),
        ('operativos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLibro',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='titulo')),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('motivo', models.CharField(blank=True, max_length=100, null=True, verbose_name='motivo')),
                ('publicado', models.BooleanField()),
                ('ilustracion', models.CharField(blank=True, max_length=100, null=True, verbose_name='ilustracion')),
                ('ilustracion_b64', models.TextField(blank=True, null=True, verbose_name='ilustracion_b64')),
                ('usar_telegram', models.BooleanField(blank=True, null=True, verbose_name='usar_telegram')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('estatus', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auxiliares.estatusoperativo', to_field='descripcion')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lugar', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auxiliares.lugar', to_field='descripcion')),
                ('tipo_operativo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auxiliares.tipooperativo', to_field='descripcion')),
            ],
            options={
                'verbose_name': 'historical Libro',
                'verbose_name_plural': 'historical Libros',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
